// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/lib/initServer"; // Initialize server on startup
import { SessionProviderWrapper } from "@/components/SessionProviderWrapper";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'https://bbfireworks.com'),
  title: {
    default: "BB Fireworks, Nilganj | Premium Fireworks & Crackers",
    template: "%s | BB Fireworks, Nilganj"
  },
  description: "Premium quality fireworks and crackers at BB Fireworks showroom in Nilganj. Browse our extensive collection of celebration fireworks, sparklers, and more.",
  keywords: ["fireworks", "crackers", "Nilganj", "BB Fireworks", "celebration", "diwali", "sparklers", "firecrackers"],
  authors: [{ name: "BB Fireworks" }],
  creator: "BB Fireworks",
  publisher: "BB Fireworks",
  applicationName: "BB Fireworks",

  // Open Graph
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: '/',
    siteName: 'BB Fireworks, Nilganj',
    title: 'BB Fireworks, Nilganj | Premium Fireworks & Crackers',
    description: 'Premium quality fireworks and crackers at BB Fireworks showroom in Nilganj.',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'BB Fireworks, Nilganj',
      },
    ],
  },

  // Twitter Card
  twitter: {
    card: 'summary_large_image',
    title: 'BB Fireworks, Nilganj | Premium Fireworks & Crackers',
    description: 'Premium quality fireworks and crackers at BB Fireworks showroom in Nilganj.',
    images: ['/og-image.jpg'],
  },

  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  // Icons
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },

  // Manifest
  manifest: '/site.webmanifest',

  // Verification
  verification: {
    // Add your verification codes here when available
    // google: 'google-site-verification-code',
    // yandex: 'yandex-verification-code',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Set theme ASAP to avoid flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const ls = localStorage.getItem('theme');
                const mql = window.matchMedia('(prefers-color-scheme: dark)');
                const wantDark = ls ? ls === 'dark' : mql.matches;
                const root = document.documentElement;
                if (wantDark) root.classList.add('dark');
                else root.classList.remove('dark');
              } catch {}
            `,
          }}
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}